spring:
  application:
    name: default-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${vault:spring.datasource.username} 
    password: ${vault:spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
